#!/data/data/com.termux/files/usr/bin/bash
#
source ${HOME}/.UMBRELLA/UMBRELLA/variables
source ${UMBRELLA}/functions
COMMANDS termux-toast termux-api
COMMANDS openssl openssl-tool

[[ $# -eq 0 ]] && {
	printf "${W}USAGE: password [ -g | -s | -n ] password for login in UMBRELLA SHELL.
  For more help type UMBRELLA [ -h | --help ] for helpper UMBRELLA CORPORATION.
	
  OPTIONS:
  -g ┆┄┄┄┄┄┄┆ --get    ┆┅┅┅┅┅┅┆ Get password
  -s ┆┄┄┄┄┄┄┆ --set    ┆┅┅┅┅┅┅┆ Set password for login, enable or disable.
  -n ┆┄┄┄┄┄┄┆ --theme  ┆┅┅┅┅┅┅┆ Create new password. \n\n";}
[[ -n $1 ]] && {
	case "$1" in
		-h|--help)
	printf "${W}USAGE: password [ -g | -s | -n ] password for login in UMBRELLA SHELL.
  For more help type UMBRELLA [ -h | --help ] for helpper UMBRELLA CORPORATION.

	OPTIONS:
  -g ┆┄┄┄┄┄┄┆ --get    ┆┅┅┅┅┅┅┆ Get password
  -s ┆┄┄┄┄┄┄┆ --set    ┆┅┅┅┅┅┅┆ Set password for login, enable or disable.
  -n ┆┄┄┄┄┄┄┆ --theme  ┆┅┅┅┅┅┅┆ Create new password. \n\n"
		  ;;
		-g|--get)
			trap ctrl_c 2;
theme cyan
			ctrl_c(){ pass Get; }
			pass Get
			;;
		-s|--set)
theme cyan
			pass set
			;;
		-n|--new)
			pass New
			;;
		*)
			about
			;;
	esac
}

