#!/data/data/com.termux/files/usr/bin/bash
#
source ${HOME}/.UMBRELLA/UMBRELLA/variables
source ${UMBRELLA}/functions
Login=$(grep "theme" ${libexec}/UMBRELLA.login|tail -n 1)
Help=$(grep "theme" ${libexec}/functions/UMBRELLA|tail -n 1)
Passw=$(grep "theme" ${libexec}/functions/password|tail -n 1)

Disable='#theme'
Cyan='theme cyan'
Red='theme red'
Dark='theme dark'

	[[ $# -eq 0 ]] && {
		printf "${W}USAGE: theme [ -l | -s | -t ]
    For more help type UMBRELLA [ -h | --help ] for helpper UMBRELLA CORPORATION.
		OPTIONS:

	-l ┆┄┄┄┄┄┄┆ --list   ┆┅┅┅┅┅┅┆ Show list for banner.
	-s ┆┄┄┄┄┄┄┆ --set    ┆┅┅┅┅┅┅┆ Enable, disable and costum the UMBRELLA wall banner.
	-t ┆┄┄┄┄┄┄┆ --theme  ┆┅┅┅┅┅┅┆ Usage for change banner. \n\n"; }
	[[ -n $1 ]] && {
	if [ $1 = '-t' ] || [ $1 = '--theme' ]; then
		case "$2" in
			cyan)
				sed -i "s|$Login|$Cyan|" ${libexec}/UMBRELLA.login
				sed -i "s|$Help|$Cyan|" ${libexec}/functions/UMBRELLA
				sed -i "s|$Passw|$Cyan|" ${libexec}/functions/password
				;;
			red)
				sed -i "s|$Login|$Red|" ${libexec}/UMBRELLA.login
				sed -i "s|$Help|$Red|" ${libexec}/functions/UMBRELLA
				sed -i "s|$Passw|$Red|" ${libexec}/functions/password
				;;
			dark)
				sed -i "s|$Login|$Dark|" ${libexec}/UMBRELLA.login
				sed -i "s|$Help|$Dark|" ${libexec}/functions/UMBRELLA
				sed -i "s|$Passw|$Dark|" ${libexec}/functions/password
				;;
			*)
				printf "${R}(⋯☣)${W}Input theme, run theme -t <banner>\n"
				;;
		esac
	elif [ $1 = '-l' ] || [ $1 = '--list' ]; then
		printf "${W}჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻\n${underline}Set banner run --> theme -t <banner>$D\n\n$W"
		printf "\n cyan ┆┅┅┅┅┅┅┆ red ┆┅┅┅┅┅┅┆ dark \n"
		printf "\n$W჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻\n";
	elif [ $1 = '-s' ] || [ $1 = '--set' ]; then
		select opt in Enable Disable Exit
		do
			[[ $opt = Exit ]] && { exit 0; }
			[[ $opt = Disable ]] && { sed -i "s|$Login|$Disable|" ${libexec}/UMBRELLA.login; }
			[[ $opt = Enable ]] && { sed -i "s|$Login|$Cyan|" ${libexec}/UMBRELLA.login; }
			break
		done
	elif [ $1 = '-h' ] || [ $1 = '--help' ]; then
		printf "${W}USAGE: theme [ -l | -s | -t ]
    For more help type UMBRELLA [ -h | --help ] for helpper UMBRELLA CORPORATION.
		OPTIONS:

	-l ┆┄┄┄┄┄┄┆ --list   ┆┅┅┅┅┅┅┆ Show list for banner.
	-s ┆┄┄┄┄┄┄┆ --set    ┆┅┅┅┅┅┅┆ Enable, disable and costum the UMBRELLA wall banner.
	-t ┆┄┄┄┄┄┄┆ --theme  ┆┅┅┅┅┅┅┆ Usage for change banner. \n\n";
	else
		about
	fi
}
