#!/data/data/com.termux/files/usr/bin/bash
#
source ${HOME}/.UMBRELLA/UMBRELLA/variables
source ${UMBRELLA}/functions

[[ $# ]] && {
  printf "${W}☣ U M B R E L L A  C O R P O R A T I O N ☣\n$v © 2023 by LAWRENCE COROY\n"
}
